controller_manager:
  ros__parameters:
    update_rate: 10
    #use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_whacker:
      type: velocity_controllers/JointGroupVelocityController

diff_cont:
  ros__parameters:
    publish_rate: 10.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link
    left_wheel_names: ['left_rear_wheel_joint']
    right_wheel_names: ['right_rear_wheel_joint']
    #left_wheel_names: ['left_front_wheel_joint','left_rear_wheel_joint']
    #right_wheel_names: ['right_front_wheel_joint','right_rear_wheel_joint']
    wheel_separation: 0.564 #<--Robot2   #0.63 # <-HB robot old: 0.3825
    wheel_radius:     0.125 #<--Robot2 0.084 # <-HB old:0.09
    use_stamped_vel: false

joint_whacker:
  ros__parameters:
    joints: ['whacker_wheel_joint']
# joint_broad:
#   ros__parameters: 
    
