twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel           #Come from VP robot_auto_vp node  
        timeout : 0.5
        priority: 50
      tracker:
        topic   : cmd_vel_tracker   #Come from tracker node - for using Phone joystick
        timeout : 0.5
        priority: 100
      joystick:
        topic   : cmd_vel_joy       # place holder for real joystic node ...
        timeout : 0.5
        priority: 10
